import jsPDF from 'jspdf';

export async function exportResultPDF(data) {
  const {
    studentName, examTitle, schoolName, teacherName,
    score, totalMarks, percentage, grade, timeTaken,
    submittedAt, violations, questions, answers,
  } = data;

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const W = doc.internal.pageSize.getWidth();

  // Header bar
  doc.setFillColor(13, 148, 136);
  doc.rect(0, 0, W, 28, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text('ExamDesk', 14, 12);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text('Smart Exam Platform', 14, 19);
  if (schoolName) {
    doc.setFontSize(9);
    doc.text(schoolName, W - 14, 12, { align: 'right' });
  }
  if (teacherName) {
    doc.text('Teacher: ' + teacherName, W - 14, 19, { align: 'right' });
  }

  // Exam title
  doc.setTextColor(30, 30, 30);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(15);
  doc.text(examTitle || 'Exam Result', W / 2, 40, { align: 'center' });

  // Student name
  doc.setFontSize(22);
  doc.setTextColor(13, 148, 136);
  doc.text(studentName || 'Student', W / 2, 52, { align: 'center' });

  // Score box
  doc.setDrawColor(229, 231, 235);
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(14, 58, W - 28, 28, 3, 3, 'FD');
  doc.setTextColor(30, 30, 30);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.text(score + ' / ' + totalMarks, W / 2, 69, { align: 'center' });
  doc.setFontSize(11);
  doc.setTextColor(100, 116, 139);
  doc.text(percentage.toFixed(1) + '%  |  Grade: ' + grade, W / 2, 79, { align: 'center' });

  // Details row
  let y = 96;
  const colW = (W - 28) / 3;
  const details = [
    ['Time Taken', timeTaken || '-'],
    ['Submitted', submittedAt || '-'],
    ['Violations', String(violations || 0)],
  ];
  details.forEach(([label, val], i) => {
    const x = 14 + i * colW + colW / 2;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(label.toUpperCase(), x, y, { align: 'center' });
    doc.setFontSize(11);
    doc.setTextColor(30, 30, 30);
    doc.text(val, x, y + 7, { align: 'center' });
  });

  // Divider
  y = 112;
  doc.setDrawColor(229, 231, 235);
  doc.line(14, y, W - 14, y);
  y += 8;

  // Questions breakdown
  if (questions && answers) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(30, 30, 30);
    doc.text('Question Breakdown', 14, y);
    y += 7;

    questions.forEach((q, i) => {
      if (y > 270) { doc.addPage(); y = 20; }
      const ans = answers[i];
      const isCorrect = !!(ans && ans.correct);

      if (isCorrect) {
        doc.setFillColor(240, 253, 244);
        doc.setDrawColor(187, 247, 208);
      } else {
        doc.setFillColor(254, 242, 242);
        doc.setDrawColor(254, 202, 202);
      }
      doc.roundedRect(14, y, W - 28, 14, 2, 2, 'FD');

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(71, 85, 105);
      const raw = String(q.text || '');
      const qLabel = 'Q' + (i + 1) + '. ' + (raw.length > 60 ? raw.substring(0, 60) + '...' : raw);
      doc.text(qLabel, 18, y + 5);

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8);
      if (isCorrect) {
        doc.setTextColor(22, 163, 74);
      } else {
        doc.setTextColor(220, 38, 38);
      }
      doc.text(isCorrect ? 'Correct' : 'Wrong', W - 18, y + 5, { align: 'right' });

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7.5);
      doc.setTextColor(100, 116, 139);
      const awarded = (ans && ans.marksAwarded) ? ans.marksAwarded : 0;
      doc.text(awarded + ' / ' + (q.marks || 1) + ' marks', W - 18, y + 11, { align: 'right' });

      y += 17;
    });
  }

  // Footer on every page
  const pageCount = doc.internal.getNumberOfPages();
  for (let p = 1; p <= pageCount; p++) {
    doc.setPage(p);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text('Generated by ExamDesk  -  Page ' + p + ' of ' + pageCount, W / 2, 290, { align: 'center' });
  }

  const safeName = studentName ? studentName.replace(/\s+/g, '_') : 'Student';
  doc.save('ExamDesk_Result_' + safeName + '.pdf');
}
